create database crm;

create table person (
    id bigint primary key generated by default as identity,
    first_name text not null,
    patronymic text,
    last_name  text not null,
    birthday date not null,
    unique (first_name, patronymic, last_name, birthday)
);

create table product (
    id bigint primary key generated by default as identity,
    person_id bigint not null constraint person_fk references person (id),
    type text not null
);

create table sensor (
    id bigint primary key generated by default as identity,
    product_id bigint not null constraint product_fk references product (id),
    type text not null
);

create table telemetry (
    id bigint primary key generated by default as identity,
    sensor_id bigint not null constraint sensor_fk references sensor (id),
    timestamp timestamp with time zone not null,
    value numeric(15, 5) not null
);

insert into person (id, first_name, patronymic, last_name, birthday)
values (1, 'Вадим', 'Петрович', 'Селиверстов', '1975-01-23'),
       (2, 'Иммануил', 'Гедеонович', 'Виторган', '1950-03-14'),
       (3, 'Петр', 'Иванович', 'Васечкин', '1990-12-11'),
       (4, 'Иван', 'Федорович', 'Крузенштерн', '1980-05-09'),
       (5, 'Илья', 'Евгеньевич', 'Михайлов', '1987-09-02');

insert into product (id, person_id, type)
values (1, 4, 'Правая рука'),
       (2, 1, 'Левая рука'),
       (3, 2, 'Правая нога'),
       (4, 3, 'Левая нога'),
       (5, 5, 'Левая рука');

insert into sensor (id, product_id, type)
values (1, 1, 'Мышца 1'),
       (2, 2, 'Мышца 2'),
       (3, 6, 'Мышца 3'),
       (4, 5, 'Мышца 4'),
       (5, 3, 'Мышца 2'),
       (6, 4, 'Мышца 6');

insert into telemetry (sensor_id, timestamp, value)
values (1, '2025-11-11T11:14:00+00', 251.0),
       (1, '2025-11-11T11:25:00+00', 251.1),
       (1, '2025-11-11T11:50:00+00', 251.7),
       (1, '2025-11-11T12:18:00+00', 252.5),
       (2, '2025-11-11T11:17:00+00', 101.3),
       (3, '2025-11-11T12:14:00+00', 510.7),
       (1, '2025-11-11T13:15:00+00', 248.0),
       (4, '2025-11-11T11:19:00+00', 23.8),
       (1, '2025-11-11T11:21:00+00', 243.0),
       (6, '2025-11-11T12:24:00+00', 1255.0),
       (5, '2025-11-11T11:44:00+00', 31.9),
       (1, '2025-11-11T14:15:00+00', 251.0);