-- create database crm;
-- grant all privileges on database crm to crm_user;

create table if not exists person (
    id bigint primary key generated by default as identity,
    first_name text not null,
    patronymic text,
    last_name  text not null,
    birthday date not null,
    unique (first_name, patronymic, last_name, birthday),
    email text not null unique
);

create table if not exists product (
    id bigint primary key generated by default as identity,
    person_id bigint not null constraint person_fk references person (id),
    type text not null
);

create table if not exists sensor (
    id bigint primary key generated by default as identity,
    product_id bigint not null constraint product_fk references product (id),
    type text not null
);

insert into person (id, first_name, patronymic, last_name, birthday, email)
values (1, 'Вадим', 'Петрович', 'Селиверстов', '1975-01-23', 'prothetic1@example.com'),
       (2, 'Иммануил', 'Гедеонович', 'Виторган', '1950-03-14', 'prothetic2@example.com'),
       (3, 'Петр', 'Иванович', 'Васечкин', '1990-12-11', 'prothetic3@example.com'),
       (4, 'Иван', 'Федорович', 'Крузенштерн', '1980-05-09', 'prothetic4@example.com'),
       (5, 'Илья', 'Евгеньевич', 'Михайлов', '1987-09-02', 'prothetic5@example.com');

insert into product (id, person_id, type)
values (1, 4, 'Правая рука'),
       (2, 1, 'Левая рука'),
       (3, 2, 'Правая нога'),
       (4, 3, 'Левая нога'),
       (5, 5, 'Левая рука');

insert into sensor (id, product_id, type)
values (1, 1, 'Мышца 1'),
       (2, 2, 'Мышца 2'),
       (3, 1, 'Мышца 3'),
       (4, 5, 'Мышца 4'),
       (5, 3, 'Мышца 2'),
       (6, 4, 'Мышца 6');